name: balkavach
description: AI Based Child Security System
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.14.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.8.3
  cloud_firestore: ^4.9.0
  firebase_messaging: ^15.3.0
  geolocator: ^10.4.0
  flutter_tts: ^4.3.0
  fl_chart: ^0.60.0
  image_picker: ^1.1.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
