name: balkavach
description: AI Based Child Security System
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.6.0
  fl_chart: ^1.2.0
  image_picker: ^1.1.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
